export class ParteSuma {
    id:                 number;
    idSuma:             string;
    cor:                string;
    fecTra:             Date;
    dstOea:             Boolean;
    dstCodTipDoc:       string;
    dstNumDoc:          string;
    dstNomRazSoc:       string;
    estAct:             string;
    datgenNumMan:       string;
    datgenNumDocEmb:    string;
    datgenFecing:       Date;
    datgenAdurecCod:    string;
    ingubimerModregDes: string;
    ingubimerTipcarDes: string;
    ingubimerAlmCod:    string;
    ingubimerAlmDes:    string;
    ingubimerSecCod:    string;
    ingubimerSecDes:    string;
    ingubimerEmipreCod: string;
    ingubimerEmipreDes: string;
    inftecDocfirUsrfir: string;
    inftecDocfirFecfir: Date;
    contotsobfalCanrec: number;
    contotsobfalPesrec: number;
    fechaRegistro:      Date;
    sync:               boolean;
}